all: first second third
first: FirstExample.cpp
	g++ -std=c++14 -O2 -Wall -pedantic -pthread FirstExample.cpp
second: FunctorWithLambda.cpp
	g++ -std=c++14 -O2 -Wall -pedantic -pthread FunctorWithLambda.cpp
third: SpecializationExample.cpp
	g++ -std=c++14 -O2 -Wall -pedantic -pthread SpecializationExample.cpp